import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it } from 'vitest'
import { INPUTS, NOTICES, stampFor, stampIn } from '../scripts/notices-stamp.ts'

// The licence page, held to the dependencies it is about.
//
// `THIRD_PARTY_NOTICES.md` is generated by `pnpm notices`, and for as long as
// that was a thing a person remembered to run, a dependency added on a Friday
// left a licence page that was wrong about what Tade ships — with nothing
// anywhere going red. Which is the same bug as a README showing a window Tade
// no longer has, and is answered the same way: by the thing that fails.
//
// What it can hold is in `notices-stamp.ts`, and it is narrower than the
// pictures' rule next door. The pictures are regenerated and compared byte for
// byte; these cannot be, because the package list is a reading of what is
// installed on the machine that read it. So this asks the question that was
// being got wrong — were the notices made after their inputs last moved? — and
// says so rather than implying more.

const ROOT = fileURLToPath(new URL('..', import.meta.url))

describe('the third-party notices', () => {
  it('were generated after everything they are made of', () => {
    const onDisk = readFileSync(join(ROOT, NOTICES), 'utf8')
    const stamp = stampIn(onDisk)
    if (stamp === null)
      throw new Error(
        `\n\n${NOTICES} carries no line saying what it was generated from.\n` +
          'Run `pnpm notices`.\n',
      )
    if (stamp !== stampFor(ROOT))
      throw new Error(
        `\n\n${NOTICES} is behind ${INPUTS.join(' and ')}.\n` +
          'One of those moved and the notices were not generated again, so the licence page is\n' +
          'wrong about what Tade ships or about what it runs. Run `pnpm notices` and commit it\n' +
          'with the change that moved them.\n',
      )
  })
})
