import { stringify } from 'yaml'
import type { ChecksManifest } from './manifest.ts'

// One list of checks that CI and your laptop both run, so "the same thing" is
// a fact instead of a hope.
//
// The workflow is generated from the manifest and never hand-edited: a step
// that runs a script that runs a command is a step whose name no longer tells
// you what ran, and two places saying what a project checks is two places to
// drift. `tade checks workflow --check` fails when the file on disk differs,
// which is itself a check.

export const WORKFLOW_PATH = '.github/workflows/ci.yml'

const HEADER = `# ${WORKFLOW_PATH} — generated by \`tade checks workflow --write\`; edit .tade/checks.yaml`

/** The workflow a manifest implies, as text. Deterministic: the same manifest, the same file. */
export function workflowFor(manifest: ChecksManifest): string {
  const runsOn = manifest.ci.runs_on.length > 0 ? manifest.ci.runs_on : ['ubuntu-latest']
  const matrix = runsOn.length > 1
  const lines: string[] = [
    HEADER,
    '',
    'name: ci',
    '',
    'on:',
    '  push:',
    '    branches: [main]',
    '  pull_request:',
    '  # So another workflow can run this exact gate instead of keeping a second',
    '  # copy of it. A release does: nothing is published until this has passed.',
    '  workflow_call:',
    '',
    "# A second push supersedes the first: the branch's old run is not news, and a",
    '# run that keeps going spends minutes on a commit nobody has any more.',
    '#',
    '# Keyed by the workflow as well as the ref, because a workflow that calls this',
    "# one runs it under the caller's ref: sharing a group with the branch's own run",
    '# would mean a release cancelling the CI beside it, or being cancelled by it.',
    'concurrency:',
    // biome-ignore lint/suspicious/noTemplateCurlyInString: GitHub's own syntax
    '  group: ${{ github.workflow }}-${{ github.ref }}',
    '  cancel-in-progress: true',
    '',
    'jobs:',
    '  check:',
    // Not a template literal: `${{ }}` is the forge's own expression syntax,
    // written out exactly as the workflow needs it.
    // biome-ignore lint/suspicious/noTemplateCurlyInString: GitHub's own syntax
    matrix ? '    runs-on: ${{ matrix.os }}' : `    runs-on: ${runsOn[0]}`,
  ]
  if (matrix) {
    lines.push(
      '    strategy:',
      // Otherwise half the matrix is cancelled the moment one row goes red, and
      // the window shows a column of nothing where the other OS should be.
      '      fail-fast: false',
      '      matrix:',
      `        os: [${runsOn.join(', ')}]`,
    )
  }
  lines.push('    steps:')
  for (const step of manifest.ci.setup) lines.push(...indented(step, 6))
  for (const check of manifest.checks) {
    if (check.skip) continue
    // A name per step, and the check's own id as that name: it is what lets
    // the window draw this local run and that CI run on one row.
    lines.push(`      - name: ${check.id}`)
    lines.push(...runLines(check.run, 8))
  }
  return `${lines.join('\n')}\n`
}

/** Whether the file on disk is what the manifest implies, ignoring trailing space. */
export function workflowMatches(onDisk: string, manifest: ChecksManifest): boolean {
  return onDisk.replace(/\s+$/, '') === workflowFor(manifest).replace(/\s+$/, '')
}

/** A command as a step's `run:`, folded when it has newlines in it. */
function runLines(run: string, at: number): string[] {
  const pad = ' '.repeat(at)
  if (!run.includes('\n')) return [`${pad}run: ${run}`]
  return [`${pad}run: |`, ...run.split('\n').map((line) => `${pad}  ${line}`)]
}

/** A setup step, written out as the manifest gave it: verbatim, indented into place. */
function indented(step: Record<string, unknown>, at: number): string[] {
  const text = stringify(step, { lineWidth: 0 }).trimEnd()
  const pad = ' '.repeat(at)
  return text
    .split('\n')
    .map((line, index) => (index === 0 ? `${pad}- ${line}` : `${pad}  ${line}`))
}
