import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { git, ROOT, repoUrl } from './repo.ts'

// CHANGELOG.md, out of the commit subjects themselves.
//
//   pnpm changelog            what it would say
//   pnpm changelog --write    write it
//
// This repository writes commit subjects as sentences — "A DSN is an endpoint,
// and leaving a field is what saves it" — and the body under each one explains
// the reasoning. Conventional-commits tooling would take that and give back
// `feat: dsn endpoint`, which says strictly less than what is already written,
// so none of that happens here: a subject is copied out verbatim, linked to its
// commit, and filed under the release it went out in. Nobody's wording is
// rewritten and no prefix is invented.
//
// What is left out is merges, which nobody wrote, and the release commit
// itself, which is bookkeeping about the very release it would appear under.

export const CHANGELOG = 'CHANGELOG.md'

/** A commit, as it is read out. */
export interface Entry {
  sha: string
  subject: string
}

/** One section of the file: a version, or what has happened since the last one. */
export interface Release {
  /** The version, or null for what is not released yet. */
  version: string | null
  /** `2026-09-22`. The tag's day, or today for what is not released yet. */
  date: string
  /** The version before it, or null when this is the first. */
  since: string | null
  entries: Entry[]
}

/**
 * The release commit, which is the one commit a changelog may not list.
 *
 * `pnpm release` writes exactly this subject, and the tag goes on it — so the
 * commit that says a release happened would otherwise be the first line of
 * the release it announces.
 */
const RELEASE_COMMIT = /^Release \d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/

const HEADER = `# Changelog

Every change to Tade, newest first, in the words whoever made it wrote. Generated by
\`pnpm changelog\` from the commit subjects themselves: this repository writes them as sentences and
explains the reasoning in the body, and a tool that reshaped them into \`feat:\` and \`fix:\` would
say less than the history already does.
`

/** The whole file, for these releases. Deterministic: the same history, the same bytes. */
export function changelogFor(releases: readonly Release[], repo: string): string {
  const parts = [HEADER, ...releases.map((release) => section(release, repo))]
  return `${parts.join('\n').trimEnd()}\n`
}

/** One release's own section, which is what a GitHub release's notes are. */
export function notesFor(release: Release, repo: string): string {
  return `${lines(release, repo).join('\n').trimEnd()}\n`
}

function section(release: Release, repo: string): string {
  return `${[heading(release, repo), '', ...lines(release, repo)].join('\n').trimEnd()}\n`
}

function heading(release: Release, repo: string): string {
  const { version, since, date } = release
  if (version === null) {
    const link = since === null ? repo : `${repo}/compare/v${since}...HEAD`
    return `## [Unreleased](${link}) — as of ${date}`
  }
  const link =
    since === null ? `${repo}/releases/tag/v${version}` : `${repo}/compare/v${since}...v${version}`
  return `## [${version}](${link}) — ${date}`
}

function lines(release: Release, repo: string): string[] {
  if (release.entries.length === 0) return ['Nothing but the release itself.']
  // The subject verbatim, then where to read the reasoning it was written with.
  return release.entries.map(
    (entry) => `- ${entry.subject} ([\`${entry.sha.slice(0, 7)}\`](${repo}/commit/${entry.sha}))`,
  )
}

/** Every `v*` tag this repository has, oldest first, ordered as versions and not as text. */
export function tags(): string[] {
  const out = git(['tag', '--list', 'v*', '--sort=version:refname'])
  return out === '' ? [] : out.split('\n')
}

/**
 * What goes in the file, read out of git.
 *
 * `pending` is the version about to be cut, which makes the top section that
 * version instead of `Unreleased`; everything else is a tag, and a tag's date
 * is the day of the commit it points at rather than the day it was pushed.
 */
export function releases(opts: { pending?: string | null; today: string }): Release[] {
  const all = tags()
  const out: Release[] = []
  for (const [index, tag] of all.entries()) {
    const previous = all[index - 1]
    out.push({
      version: tag.slice(1),
      date: git(['log', '-1', '--format=%as', tag]),
      since: previous === undefined ? null : previous.slice(1),
      entries: between(previous ?? null, tag),
    })
  }
  const last = all.at(-1)
  const head = between(last ?? null, 'HEAD')
  // A version that is already the last tag is the section just written, not a
  // second one: this is what the release workflow asks for, standing on the
  // tag it is publishing.
  const pending = (opts.pending ?? null) === last?.slice(1) ? null : (opts.pending ?? null)
  // An empty `Unreleased` section is a heading saying nothing; a release with
  // nothing in it is worth saying, which is why only this one is dropped.
  if (head.length > 0 || pending !== null) {
    out.push({
      version: pending,
      date: opts.today,
      since: last === undefined ? null : last.slice(1),
      entries: head,
    })
  }
  return out.reverse()
}

/** The commits in `from..to`, newest first, without the merges or the release commit. */
function between(from: string | null, to: string): Entry[] {
  // `%x1f` and not the byte: a source file holding a control character is one
  // every grep in the repository treats as binary. `test/source.test.ts` holds
  // this repository to that.
  const range = from === null ? to : `${from}..${to}`
  const out = git(['log', '--no-merges', '--format=%H%x1f%s', range])
  if (out === '') return []
  return out
    .split('\n')
    .map((line) => {
      const [sha = '', subject = ''] = line.split('\x1f')
      return { sha, subject }
    })
    .filter((entry) => entry.sha !== '' && !RELEASE_COMMIT.test(entry.subject))
}

/** Today, as git writes a date. Taken from the caller so the same run says one day throughout. */
export function today(now: Date): string {
  return now.toISOString().slice(0, 10)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2)
  const after = (flag: string): string | null => {
    const at = args.indexOf(flag)
    return at === -1 ? null : (args[at + 1] ?? null)
  }
  const repo = repoUrl()
  const all = releases({ pending: after('--version'), today: today(new Date()) })
  const text = changelogFor(all, repo)
  // The top section on its own is what a forge shows as a release's notes.
  const notes = after('--notes')
  const top = all[0]
  if (notes !== null && top !== undefined) {
    writeFileSync(notes, notesFor(top, repo))
    process.stdout.write(`${notes}: ${top.entries.length} entries\n`)
  }
  if (args.includes('--write')) {
    writeFileSync(join(ROOT, CHANGELOG), text)
    process.stdout.write(`${CHANGELOG}: ${text.split('\n').length - 1} lines\n`)
  } else if (notes === null) process.stdout.write(text)
}
