import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { COMMAND, PUBLISHED, ROOT, repoUrl, rootManifest } from './repo.ts'

// The second way to get Tade, and the one place its formula is written.
//
// Homebrew installs the npm package: the `url` in the formula is the very
// tarball `npm i -g tade-sh` downloads, so one publish feeds both ways in and
// nothing here can be a different version of Tade than npm has. A formula that
// built from this repository instead would be a second release with its own
// gate to keep green, and a second thing to be wrong.
//
// So there are exactly two lines that change per version — `url` and `sha256` —
// and this writes the whole file rather than editing those two, because a
// generator that patches a file it did not write is a generator that has to
// understand Ruby. `test/homebrew.test.ts` holds the output to what Homebrew's
// own audit wants (a `desc` with no article and no formula name in it, the
// license out of the manifest, the registry URL the livecheck strategy reads)
// and to the one decision in it, which is `ignore_scripts: false`.
//
// Nothing in here is on the gate's path: the hash can only be taken from bytes
// the registry already has, so this runs after a publish and never before one.
// The pure parts are exported for the test; the network is the CLI's alone.

/** The formula, repo-relative. Named for the command, which is what `brew install` resolves. */
export const FORMULA = `scripts/release/homebrew/${COMMAND}.rb`

/** The default when nothing is asked for: what this checkout says it is. */
export const DEFAULT_VERSION = (): string => rootManifest().version

/**
 * The registry URL for one version.
 *
 * `registry.npmjs.org` by name and not whatever `npm view dist.tarball` says —
 * on a machine behind a registry proxy that answers with the proxy's own host,
 * which is a URL nobody else can fetch. It is also the host Homebrew's `Npm`
 * livecheck strategy matches, which is what lets a tap notice a new version
 * without being told.
 */
export function tarballUrl(version: string, published: string = PUBLISHED): string {
  return `https://registry.npmjs.org/${published}/-/${published}-${version}.tgz`
}

/**
 * `tade` → `Tade`, which is the class name Homebrew requires of `tade.rb`.
 *
 * Hyphens too (`tade-sh` → `TadeSh`), so renaming the command cannot quietly
 * produce a formula Ruby will not load.
 */
export function className(command: string = COMMAND): string {
  return command
    .split(/[-_]/)
    .map((part) => (part[0] ?? '').toUpperCase() + part.slice(1))
    .join('')
}

/**
 * Homebrew's `desc` out of the manifest's description.
 *
 * Its audit refuses a leading article, a trailing full stop, and the formula's
 * own name inside the sentence — so the description is not copied, it is
 * narrowed, and the test holds the result to all three rather than to a string
 * somebody typed twice.
 */
export function descFor(description: string = rootManifest().description): string {
  const said = description
    .replace(/^(?:an?|the)\s+/i, '')
    .replace(/\.\s*$/, '')
    .trim()
  return (said[0] ?? '').toUpperCase() + said.slice(1)
}

export interface Formula {
  version: string
  sha256: string
}

/** The whole file, for a version whose bytes the registry already has. */
export function formulaFor({ version, sha256 }: Formula): string {
  const root = rootManifest()
  return `# What Homebrew installs, and the one line in it that is a decision.
#
# Homebrew is a second way to get Tade and not a second thing to build: the
# \`url\` below is the very tarball \`npm i -g ${PUBLISHED}\` downloads, so one publish
# feeds both and nothing here can be a different version of Tade than npm has.
#
# Generated by \`pnpm homebrew\`, which takes the hash from the registry — so the
# two lines that change per version are \`url\` and \`sha256\`, and neither was
# typed. Do not hand-edit this: \`scripts/release/homebrew.ts\` is where the text
# is, and \`test/homebrew.test.ts\` holds it to what Homebrew's audit wants.
class ${className()} < Formula
  include Language::Node::Shebang

  desc "${descFor(root.description)}"
  homepage "${repoUrl(root)}"
  url "${tarballUrl(version)}"
  sha256 "${sha256}"
  license "${root.license}"

  depends_on "node"

  def install
    # \`ignore_scripts: false\`, against Homebrew's default, and the one decision
    # in this file. The tarball's two install scripts are both about node-pty,
    # which is a binary rather than a file: \`preinstall\` refuses early on a
    # machine with no toolchain instead of leaving node-gyp to say it in forty
    # lines, and \`postinstall\` puts the executable bit back on node-pty's
    # \`spawn-helper\`, without which every lane fails with \`posix_spawnp failed.\`
    # and no other word. Installed with scripts ignored this is a \`${COMMAND}\` that
    # cannot open a terminal, which is all of Tade.
    system "npm", "install", *std_npm_args(ignore_scripts: false)

    # The published bin says \`#!/usr/bin/env node\`, which is whatever node is
    # first on the PATH of whoever runs it — an older one answers \`nodeTooOld\`,
    # and any other major answers \`nativeTrouble\`, because node-pty was just
    # compiled against this one. Point it at the node this formula depends on,
    # so \`${COMMAND}\` is not a different program per shell.
    rewrite_shebang detected_node_shebang, libexec/"lib/node_modules/${PUBLISHED}/packages/cli/src/bin.js"

    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    # Answering \`--version\` at all means every package in the tarball resolved
    # through its generated \`exports\` map, because the CLI builds its whole
    # command tree at load. The version is Homebrew's own, so this file has no
    # third line to keep in step with a release.
    assert_equal version.to_s, shell_output("#{bin}/${COMMAND} --version").strip

    # \`status\` is the one that reads git, the journal and the processes, and it
    # is held never to throw: somewhere that is not a repository it is a partial
    # answer with warnings on it, which is what this asks for. Its home is the
    # test's own directory, because a test may not touch anybody's.
    ENV["TADE_HOME"] = testpath/"home"
    ENV["TADE_NO_GH"] = "1"
    assert_match "projects", shell_output("#{bin}/${COMMAND} status --json")

    # The one thing in the tarball that is a binary rather than a file, loaded.
    # This is what \`ignore_scripts: false\` above is for, and on Linux — where
    # node-pty ships no prebuild and is always compiled — it is the difference
    # between a \`${COMMAND}\` that opens terminals and one that cannot: an install
    # whose scripts were skipped gets this far and no further.
    cd libexec/"lib/node_modules/${PUBLISHED}" do
      system Formula["node"].opt_bin/"node", "-e", "require('node-pty')"
    end
  end
end
`
}

/**
 * The hash Homebrew needs, from the bytes the registry is serving.
 *
 * A 404 here is the ordinary case and not a failure of this script: the version
 * is not published yet, and the publish job is what puts it there.
 */
export async function sha256Of(url: string): Promise<string> {
  const answer = await fetch(url)
  if (!answer.ok)
    throw new Error(
      `${url}\nThe registry answered ${answer.status}. ` +
        'A formula can only name bytes that are already published —\n' +
        'so this runs after the release workflow has published, never before it.',
    )
  return createHash('sha256')
    .update(new Uint8Array(await answer.arrayBuffer()))
    .digest('hex')
}

/**
 * The tap `--try` builds in, and the one name it may ever use.
 *
 * Homebrew 7 refuses a formula that is not in a tap — `brew install ./tade.rb`
 * is gone — so proving one means making a tap, and a tap this throws away.
 * Never a real one: a scratch tap that happened to be called what the published
 * tap is called would shadow it on the machine of whoever ran this.
 */
export const SCRATCH = 'tade-trying/scratch'

function brew(args: string[], opts: { quiet?: boolean } = {}): string {
  try {
    return execFileSync('brew', args, {
      encoding: 'utf8',
      stdio: opts.quiet ? ['ignore', 'pipe', 'pipe'] : ['ignore', 'inherit', 'inherit'],
      maxBuffer: 64 * 1024 * 1024,
    })
  } catch (err) {
    // What `execFileSync` throws names a signal and a pid and not the command,
    // and under `inherit` its `stderr` is empty because Homebrew already said
    // its piece on the terminal. So: which command, and nothing it cannot know.
    const said = (err as { code?: string }).code === 'ENOENT' ? ' — no `brew` on this machine' : ''
    throw new Error(`brew ${args.join(' ')} failed${said}`)
  }
}

/**
 * Build the formula as it stands and run its test block, then take it all off
 * again.
 *
 * The same four acts the workflow does on macOS before it opens a pull request,
 * so a person and the machine prove a formula the same way. It builds node-pty
 * and better-sqlite3 from source — Homebrew always passes `--build-from-source`,
 * because a bottle may not carry somebody else's prebuilt binary — so it wants
 * a working toolchain and a few minutes.
 *
 * It leaves nothing behind: the tap, the install and the trust entry
 * `brew install <tap>/<formula>` writes all come off in the `finally`, whether
 * the build worked or not.
 */
export function tryIt(): void {
  const repository = brew(['--repository'], { quiet: true }).trim()
  // Because the `finally` below removes this directory, and a path worked out
  // from an answer that was not one would be a path somewhere else entirely.
  if (!repository.startsWith('/'))
    throw new Error(`brew --repository answered ${repository || '(nothing)'}, which is not a path`)
  const where = join(
    repository,
    'Library/Taps',
    ...SCRATCH.split('/').map((part, at) => (at === 1 ? `homebrew-${part}` : part)),
  )
  const formula = `${SCRATCH}/${COMMAND}`
  try {
    rmSync(where, { recursive: true, force: true })
    brew(['tap-new', '--no-git', SCRATCH])
    mkdirSync(join(where, 'Formula'), { recursive: true })
    copyFileSync(join(ROOT, FORMULA), join(where, 'Formula', `${COMMAND}.rb`))
    // Typing the tap's full name is what trusts the formula, which is the one
    // thing Homebrew 7 asks of anything outside its own taps.
    brew(['install', '--build-from-source', '--formula', formula])
    brew(['test', formula])
    process.stdout.write(`\n${formula} built from source and passed its test block.\n`)
  } finally {
    // Each on its own, because a teardown that stops at the first thing that
    // was never made leaves the rest of it on the machine — and what it could
    // not take off is **said**, because a `${COMMAND}` left in Homebrew's bin
    // shadows the one somebody develops with and nothing else would mention it.
    const left: string[] = []
    for (const args of [
      ['uninstall', '--formula', formula],
      ['untrust', '--formula', formula],
      ['untap', SCRATCH],
    ]) {
      try {
        brew(args, { quiet: true })
      } catch {
        left.push(`brew ${args.join(' ')}`)
      }
    }
    rmSync(where, { recursive: true, force: true })
    // `uninstall` and `untrust` fail where there was nothing installed to take
    // off, which is every run that stopped before the install — so this is only
    // worth saying when the install is the thing that may still be there.
    if (left.length === 3)
      process.stderr.write(`\nNothing was installed, so nothing was taken off.\n`)
    else if (left.length > 0)
      process.stderr.write(
        `\nStill on this machine — run these yourself:\n  ${left.join('\n  ')}\n`,
      )
  }
}

async function main(argv: string[]): Promise<void> {
  if (argv.includes('--try')) {
    tryIt()
    return
  }

  const at = argv.indexOf('--version')
  const version = at === -1 ? DEFAULT_VERSION() : (argv[at + 1] ?? '')
  if (!/^\d+\.\d+\.\d+/.test(version))
    throw new Error(`${version || '(nothing)'} is not a version: 0.2.0, or 0.2.0-rc.1`)

  const url = tarballUrl(version)
  const sha256 = await sha256Of(url)

  if (argv.includes('--print')) {
    // For the workflow, which appends these to `$GITHUB_OUTPUT` rather than
    // reading them out of a log.
    process.stdout.write(`version=${version}\nurl=${url}\nsha256=${sha256}\n`)
    return
  }

  const path = join(ROOT, FORMULA)
  const written = formulaFor({ version, sha256 })
  const before = readFileSync(path, 'utf8')
  writeFileSync(path, written)
  process.stdout.write(
    `${before === written ? 'unchanged' : 'wrote'} ${FORMULA} for ${version}\n` +
      `  ${url}\n  sha256 ${sha256}\n`,
  )
}

if (process.argv[1] === new URL(import.meta.url).pathname) await main(process.argv.slice(2))
