# What Homebrew installs, and the one line in it that is a decision.
#
# Homebrew is a second way to get Tade and not a second thing to build: the
# `url` below is the very tarball `npm i -g tade-sh` downloads, so one publish
# feeds both and nothing here can be a different version of Tade than npm has.
#
# Generated by `pnpm homebrew`, which takes the hash from the registry — so the
# two lines that change per version are `url` and `sha256`, and neither was
# typed. Do not hand-edit this: `scripts/release/homebrew.ts` is where the text
# is, and `test/homebrew.test.ts` holds it to what Homebrew's audit wants.
class Tade < Formula
  include Language::Node::Shebang

  desc "Voice-first control room for running coding agents on your own machine"
  homepage "https://github.com/mujacica/tade"
  url "https://registry.npmjs.org/tade-sh/-/tade-sh-0.1.1.tgz"
  sha256 "94f6a0321a2d0dba5da018600e36b25006df3800bb2d425818fb7bf8e9e62615"
  license "MIT"

  depends_on "node"

  def install
    # `ignore_scripts: false`, against Homebrew's default, and the one decision
    # in this file. The tarball's two install scripts are both about node-pty,
    # which is a binary rather than a file: `preinstall` refuses early on a
    # machine with no toolchain instead of leaving node-gyp to say it in forty
    # lines, and `postinstall` puts the executable bit back on node-pty's
    # `spawn-helper`, without which every lane fails with `posix_spawnp failed.`
    # and no other word. Installed with scripts ignored this is a `tade` that
    # cannot open a terminal, which is all of Tade.
    system "npm", "install", *std_npm_args(ignore_scripts: false)

    # The published bin says `#!/usr/bin/env node`, which is whatever node is
    # first on the PATH of whoever runs it — an older one answers `nodeTooOld`,
    # and any other major answers `nativeTrouble`, because node-pty was just
    # compiled against this one. Point it at the node this formula depends on,
    # so `tade` is not a different program per shell.
    rewrite_shebang detected_node_shebang, libexec/"lib/node_modules/tade-sh/packages/cli/src/bin.js"

    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    # Answering `--version` at all means every package in the tarball resolved
    # through its generated `exports` map, because the CLI builds its whole
    # command tree at load. The version is Homebrew's own, so this file has no
    # third line to keep in step with a release.
    assert_equal version.to_s, shell_output("#{bin}/tade --version").strip

    # `status` is the one that reads git, the journal and the processes, and it
    # is held never to throw: somewhere that is not a repository it is a partial
    # answer with warnings on it, which is what this asks for. Its home is the
    # test's own directory, because a test may not touch anybody's.
    ENV["TADE_HOME"] = testpath/"home"
    ENV["TADE_NO_GH"] = "1"
    assert_match "projects", shell_output("#{bin}/tade status --json")

    # The one thing in the tarball that is a binary rather than a file, loaded.
    # This is what `ignore_scripts: false` above is for, and on Linux — where
    # node-pty ships no prebuild and is always compiled — it is the difference
    # between a `tade` that opens terminals and one that cannot: an install
    # whose scripts were skipped gets this far and no further.
    cd libexec/"lib/node_modules/tade-sh" do
      system Formula["node"].opt_bin/"node", "-e", "require('node-pty')"
    end
  end
end
