import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

// What the notices were generated from, written into the notices themselves.
//
// `THIRD_PARTY_NOTICES.md` is generated, and nothing made anybody regenerate
// it: a dependency added and `pnpm notices` forgotten leaves a licence page
// that is wrong about what Tade ships, and every test still passes.
//
// It cannot be held the way the README's pictures are — regenerate, compare
// the bytes — because the package list is a reading of what is *installed*,
// and that differs by machine: `@biomejs/cli-darwin-arm64` is in the file on
// this laptop and could never be on an Ubuntu runner, and the licence texts
// come out of the store, where a package nobody installed has none. So what
// is held instead is the question that was actually being got wrong: were
// these made after their inputs last moved?
//
// Two inputs and no others. `pnpm-lock.yaml` decides every package, version
// and licence in the file — no dependency can change without it changing —
// and `scripts/notices.ts` holds the rest: the programs, services and data
// Tade uses without installing, which are written by hand.
//
// It is honest about its bound: it says the notices were generated after
// their inputs last moved. It does not say nobody edited them by hand
// afterwards, and it is not a reading of what is in them.

/** The generated file, repo-relative. */
export const NOTICES = 'THIRD_PARTY_NOTICES.md'

/** Everything the notices are made of. Either one moving means run it again. */
export const INPUTS = ['pnpm-lock.yaml', 'scripts/notices.ts'] as const

/** The inputs as they are now, in twelve hex characters. */
export function fingerprint(root: string): string {
  const hash = createHash('sha256')
  for (const path of INPUTS) hash.update(readFileSync(join(root, path)))
  return hash.digest('hex').slice(0, 12)
}

/** What the notices say about themselves, saying what they were made from. */
export function stampFor(root: string): string {
  const named = INPUTS.map((path) => `\`${path}\``).join(' and ')
  return (
    `Generated by \`pnpm notices\` from ${named} · \`${fingerprint(root)}\`.\n` +
    'Run it again after changing either: a test fails while this is behind them.'
  )
}

/** What the notices on disk say about themselves, or `null` where they say none. */
export function stampIn(text: string): string | null {
  return /^Generated by `pnpm notices` from .+ · `[0-9a-f]{12}`\.\n.+$/m.exec(text)?.[0] ?? null
}
